services:
  nginx:
    container_name: meetphp_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certificate.crt:/etc/nginx/conf.d/certificate.crt
      - ./docker/nginx/certificate.key:/etc/nginx/conf.d/certificate.key
    ports:
      - "8005:80"
    depends_on:
      - php
    networks:
      laravel:
        ipv4_address: 172.19.0.2

  php:
    container_name: meetphp_php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/queue-worker.supervisor.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./docker/php/queue-email.supervisor.conf:/etc/supervisor/conf.d/queue-email.conf
      - ./:/var/www/html
    networks:
      laravel:
        ipv4_address: 172.19.0.3

  redis:
    image: redis:latest
    container_name: meetphp_redis
    ports:
      - "6380:6379"
    networks:
      laravel:
        ipv4_address: 172.19.0.4

  mariadb:
    container_name: meetphp_db
    image: mariadb:10.4.26
    environment:
      MYSQL_ROOT_PASSWORD: mds3112
    volumes:
    - ./../mysqldata/meetphp:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      laravel:
        ipv4_address: 172.19.0.7

networks:
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16